stages:
  - build-sdl2
  - build-glfw
  - deploy
  - publish

build-glfw-web:
  artifacts:
    name: "$CI_COMMIT_REF_NAME"
    paths:
      - examples/example_glfw_opengl3
  variables:
    BUILD_TARGET: web
    GIT_STRATEGY: clone
  tags:
    - web-runner
  stage: build-glfw
  script:
    - cd examples/example_glfw_opengl3
    - export PWD_WEB=$PWD
    - cd /build/emsdk/
    - . ./emsdk_env.sh
    - cd $PWD_WEB
    - make -f Makefile.emscripten
  
build-glfw-windows:
  artifacts:
    name: "$CI_COMMIT_REF_NAME"
    paths:
      - examples/example_glfw_opengl3
  variables:
    BUILD_TARGET: windows
    GIT_STRATEGY: clone
    OS: Windows_NT
    PKG_CONFIG_PATH: /mingw64/lib/pkgconfig
    CPATH: /usr/local/x86_64-w64-mingw32/include
    MINGW: /mingw64
    CXX: x86_64-w64-mingw32-g++
  before_script:
    - export PATH=$PATH:$MINGW
    - ld --verbose | grep SEARCH_DIR | tr -s ' ;' \\012 | grep ^SEARCH_DIR | sed 's/^SEARCH_DIR("=\?\([^"]\+\)");/\1/'
    - grep -v "UNAME_S := \$(shell uname -s)" examples/example_glfw_opengl3/Makefile > examples/example_glfw_opengl3/temp && mv examples/example_glfw_opengl3/temp examples/example_glfw_opengl3/Makefile
    - echo "Removed UNAME_S assignment from Makefile"
  tags:
    - windows-runner
  stage: build-glfw
  script:
    - cd examples/example_glfw_opengl3
    - make

build-glfw-windows32:
  artifacts:
    name: "$CI_COMMIT_REF_NAME"
    paths:
      - examples/example_glfw_opengl3
  variables:
    BUILD_TARGET: windows32
    GIT_STRATEGY: clone
    OS: Windows_NT
    PKG_CONFIG_PATH: /mingw64/lib/pkgconfig
    CPATH: /usr/local/i686-w64-mingw32/include
    MINGW: /mingw
    CXX: i686-w64-mingw32-g++
  before_script:
    - export PATH=$PATH:$MINGW
    - grep -v "UNAME_S := \$(shell uname -s)" examples/example_glfw_opengl3/Makefile > examples/example_glfw_opengl3/temp && mv examples/example_glfw_opengl3/temp examples/example_glfw_opengl3/Makefile
    - echo "Removed UNAME_S assignment from Makefile"
  tags:
    - windows32-runner
  stage: build-glfw
  script:
    - cd examples/example_glfw_opengl3
    - make

build-glfw-linux:
  artifacts:
    name: "$CI_COMMIT_REF_NAME"
    paths:
      - examples/example_glfw_opengl3
  variables:
    BUILD_TARGET: linux
    GIT_STRATEGY: clone
  tags:
    - linux-runner
  stage: build-glfw
  script:
    - cd examples/example_glfw_opengl3
    - make

build-sdl2-web:
  artifacts:
    name: "$CI_COMMIT_REF_NAME"
    paths:
      - examples/example_sdl2_opengl3
  variables:
    BUILD_TARGET: web
    GIT_STRATEGY: clone
  tags:
    - web-runner
  stage: build-sdl2
  script:
    - cd examples/example_sdl2_opengl3
    - export PWD_WEB=$PWD
    - cd /build/emsdk/
    - . ./emsdk_env.sh
    - cd $PWD_WEB
    - make -f Makefile.emscripten
  
build-sdl2-windows:
  variables:
    BUILD_TARGET: windows
    GIT_STRATEGY: clone
    SDL2_CONFIG: /usr/local/cross-tools/x86_64-w64-mingw32/bin/
    OS: Windows_NT
    PKG_CONFIG_PATH: /usr/local/cross-tools/x86_64-w64-mingw32/lib/pkgconfig
    CPATH: /usr/local/x86_64-w64-mingw32/include
    MINGW: /mingw64
    CXX: x86_64-w64-mingw32-g++
  before_script:
    - export PATH=$PATH:$SDL2_CONFIG
    - alias uname='echo Windows_NT'
    - grep -v "UNAME_S := \$(shell uname -s)" examples/example_sdl2_opengl3/Makefile > examples/example_sdl2_opengl3/temp && mv examples/example_sdl2_opengl3/temp examples/example_sdl2_opengl3/Makefile
    - echo "Removed UNAME_S assignment from Makefile"
  tags:
    - windows-runner
  stage: build-sdl2
  script:
    - cd examples/example_sdl2_opengl3
    - make

build-sdl2-windows32:
  variables:
    BUILD_TARGET: windows32
    GIT_STRATEGY: clone
    SDL2_CONFIG: /usr/local/cross-tools/i686-w64-mingw32/bin/
    OS: Windows_NT
    PKG_CONFIG_PATH: /usr/local/cross-tools/i686-w64-mingw32/lib/pkgconfig
    CPATH: /usr/local/i686-w64-mingw32/include
    MINGW: /mingw
    CXX: i686-w64-mingw32-g++
  before_script:
    - export PATH=$PATH:$SDL2_CONFIG
    - grep -v "UNAME_S := \$(shell uname -s)" examples/example_sdl2_opengl3/Makefile > examples/example_sdl2_opengl3/temp && mv examples/example_sdl2_opengl3/temp examples/example_sdl2_opengl3/Makefile
    - echo "Removed UNAME_S assignment from Makefile"
  tags:
    - windows32-runner
  stage: build-sdl2
  script:
    - cd examples/example_sdl2_opengl3
    - make

build-sdl2-linux:
  artifacts:
    name: "$CI_COMMIT_REF_NAME"
    paths:
      - examples/example_sdl2_opengl3
  variables:
    BUILD_TARGET: linux
    GIT_STRATEGY: clone
  tags:
    - linux-runner
  stage: build-sdl2
  script:
    - cd examples/example_sdl2_opengl3
    - make

deploy-sdl2-web:
  tags:
    - web-server
  stage: deploy
  script:
    - mkdir -p /usr/share/nginx/html/sdl2
    - cp examples/example_sdl2_opengl3/web/* /usr/share/nginx/html/sdl2/
  needs:
    - job: build-sdl2-web
      artifacts: true

deploy-glfw-web:
  tags:
    - web-server
  stage: deploy
  script:
    - mkdir -p /usr/share/nginx/html/glfw
    - cp examples/example_glfw_opengl3/web/* /usr/share/nginx/html/glfw/
  needs:
    - job: build-glfw-web
      artifacts: true

publish-source-code:
  tags:
    - linux-runner
  stage: publish
  script:
    - mkdir -p ./src/backends
    - mkdir -p ./src/imgui
    - cp -r backends/imgui_impl_opengl3.cpp ./src/backends
    - cp -r backends/imgui_impl_opengl3.h ./src/backends
    - cp -r backends/imgui_impl_opengl3_loader.h ./src/backends
    - cp -r backends/imgui_impl_glfw.cpp ./src/backends
    - cp -r backends/imgui_impl_glfw.h ./src/backends
    - cp -r backends/imgui_impl_sdl2.cpp ./src/backends
    - cp -r backends/imgui_impl_sdl2.h ./src/backends
    - cp -r backends/imgui_impl_sdlrenderer2.cpp ./src/backends
    - cp -r backends/imgui_impl_sdlrenderer2.h ./src/backends
    - cp -r imgui_draw.cpp ./src/imgui
    - cp -r imgui_internal.h ./src/imgui
    - cp -r imgui_tables.cpp ./src/imgui
    - cp -r imgui_widgets.cpp ./src/imgui
    - cp -r imgui_demo.cpp ./src/imgui
    - cp -r imconfig.h ./src/imgui
    - cp -r imgui.cpp ./src/imgui
    - cp -r imgui.h ./src/imgui
    - cp -r imstb_rectpack.h ./src/imgui
    - cp -r imstb_textedit.h ./src/imgui
    - cp -r imstb_truetype.h ./src/imgui
  artifacts:
    name: "$CI_PROJECT_NAME"
    paths:
      - ./src