stages:
  - build-all
  - deploy

build-web:
  artifacts:
    name: "$CI_COMMIT_REF_NAME"
    paths:
      - examples/example_sdl2_opengl3
  variables:
    BUILD_TARGET: web
    GIT_STRATEGY: clone
  tags:
    - web-runner
  stage: build-all
  script:
    - cd examples/example_sdl2_opengl3
    - export PWD_WEB=$PWD
    - cd /build/emsdk/
    - . ./emsdk_env.sh
    - cd $PWD_WEB
    - make -f Makefile.emscripten
  
build-windows:
  variables:
    BUILD_TARGET: windows
    GIT_STRATEGY: clone
    MINGW: /mingw64
  tags:
    - windows-runner
  stage: build-all
  script:
    - cd examples/example_null
    - make

build-windows32:
  variables:
    BUILD_TARGET: windows32
    GIT_STRATEGY: clone
    MINGW: /mingw64
  tags:
    - windows32-runner
  stage: build-all
  script:
    - cd examples/example_null
    - make

build-linux:
  artifacts:
    name: "$CI_COMMIT_REF_NAME"
    paths:
      - examples/example_sdl2_opengl3
  variables:
    BUILD_TARGET: linux
    GIT_STRATEGY: clone
  tags:
    - linux-runner
  stage: build-all
  script:
    - cd examples/example_sdl2_opengl3
    - make

run-web-server:
  tags:
    - web-server
  stage: deploy
  script:
    - mkdir -p /usr/share/nginx/html/demo
    - cp examples/example_sdl2_opengl3/web/* /usr/share/nginx/html/demo/
  needs:
    - job: build-web
      artifacts: true

publish-source-code:
  tags:
    - linux-runner
  stage: deploy
  script:
    - mkdir -p ./publish/backends
    - cp -r backends/imgui_impl_opengl3.cpp ./publish/backends
    - cp -r backends/imgui_impl_opengl3.h ./publish/backends
    - cp -r backends/imgui_impl_opengl3_loader.h ./publish/backends
    - cp -r backends/imgui_impl_glfw.cpp ./publish/backends
    - cp -r backends/imgui_impl_glfw.h ./publish/backends
    - cp -r backends/imgui_impl_sdl2.cpp ./publish/backends
    - cp -r backends/imgui_impl_sdl2.h ./publish/backends
    - cp -r backends/imgui_impl_sdlrenderer2.cpp ./publish/backends
    - cp -r backends/imgui_impl_sdlrenderer2.h ./publish/backends
    - cp -r imgui_draw.cpp ./publish
    - cp -r imgui_internal.h ./publish
    - cp -r imgui_tables.cpp ./publish
    - cp -r imgui_widgets.cpp ./publish
    - cp -r imgui_demo.cpp ./publish
    - cp -r imconfig.h ./publish
    - cp -r imgui.cpp ./publish
    - cp -r imgui.h ./publish
    - cp -r imstb_rectpack.h ./publish
    - cp -r imstb_textedit.h ./publish
    - cp -r imstb_truetype.h ./publish
  artifacts:
    name: imgui
    paths:
      - ./publish